export const listaProdutos = [
  { codigo: 1, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 1 },
  { codigo: 2, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 4 },
  { codigo: 3, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 3 },
  { codigo: 4, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 6 },
  { codigo: 5, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 8 },
  { codigo: 6, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 7, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 8, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 9, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 10, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 100, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 110, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 123, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 1234, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 12345, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 123456, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
  { codigo: 99999, unidade: "UN", preco: 2.99, produto: "goiabada", qtde: 9 },
];
