import { useEffect, useState } from "react";
import { Produto } from "../App";
import { Tecla } from "./tecla";

export function Teclado(props: { handleComando: Function }) {
  return (
    <div className="w-full h-2/5 bg-gray-200">
      <div className="grid h-full grid-cols-4 gap-1 p-1 grid-flow-row">
        <Tecla
          action={props.handleComando}
          numero={"7"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"8"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"9"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"C"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"4"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"5"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"6"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"<"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"1"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"2"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"3"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"Enter"}
          altura={"row-span-2"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"-"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={"0"}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
        <Tecla
          action={props.handleComando}
          numero={","}
          altura={"row-span-1"}
          largura={"col-span-1"}
        />
      </div>
    </div>
  );
}
